#ifndef RCC_H
#define RCC_H

typedef struct
{
	__RW CR;
	__RW ICSCR;
	__RW CFGR;
	__RW PLLCFGR;
	RESERVED;
	RESERVED;
	__RW CIER;
	__RO CIFR;
	__WO CICR;
	RESERVED;
	__RW AHB1RSTR;
	__RW AHB2RSTR;
	__RW AHB3RSTR;
	RESERVED;
	__RW APB1RSTR1;
	__RW APB1RSTR2;
	__RW APB2RSTR;
	RESERVED;
	__RW AHB1ENR;
	__RW AHB2ENR;
	__RW AHB3ENR;
	RESERVED;
	__RW APB1ENR1;
	__RW APB1ENR2;
	__RW APB2ENR;
	RESERVED;
	__RW AHB1SMENR;
	__RW AHB2SMENR;
	__RW AHB3SMENR;
	RESERVED;
	__RW APB1SMENR1;
	__RW APB1SMENR2;
	__RW APB2SMENR;
	RESERVED;
	__RW CCIPR;
	RESERVED;
	__RW BDCR;
	__RW CSR;
	__RW CRRCR;
	__RW CCIPR2;
}reset_and_control_clock_type;

#define RCC_BASE_ADDRESS (0x40021000UL)
#define RCC ((reset_and_control_clock_type*) RCC_BASE_ADDRESS)

#define RCC_CR_PLLRDY (0x1UL << 25)
#define RCC_CR_PLLON (0x1UL << 24)
#define RCC_CR_HSERDY (0x1UL << 17)
#define RCC_CR_HSEON (0x1UL << 16)
#define RCC_CR_HSIRDY (0x1UL << 10)
#define RCC_CR_HSION (0x1UL << 8)


#define RCC_PLLCFGR_PLLR_Pos 25
#define RCC_PLLCFGR_PLLREN (0x1UL << 24)

#define RCC_PLLCFGR_PLLN_Msk (0x7FUL << 8)
#define RCC_PLLCFGR_PLLN(val) (((val) & 0x7FUL) << 8)

#define RCC_PLLCFGR_PLLSRC_Msk 0x3UL
#define RCC_PLLCFGR_PLLSRC_MSI 0x1UL
#define RCC_PLLCFGR_PLLSRC_HSI16 0x2UL
#define RCC_PLLCFGR_PLLSRC_HSE RCC_PLLCFGR_PLLSRC_Msk


#define RCC_CFGR_STOPWUCK (0x1UL << 15)
#define RCC_CFGR_SWS_Msk (0x3UL << 2)
#define RCC_CFGR_SWS_PLL RCC_CFGR_SWS_Msk

#define RCC_CFGR_SW_PLL 0x3UL

#define RCC_AHB2ENR_GPIOAEN 0x1UL
#define RCC_AHB2ENR_GPIOBEN (0x1UL << 1)

#define RCC_APB1ENR1_PWREN (0x1UL << 28)
#define RCC_APB1ENR1_I2C1EN (0x1UL << 21)

#define RCC_APB2ENR_SYSCFGEN 0x1UL
#define RCC_APB2ENR_SYSCFGEN 0x1UL


#define RCC_CCIPR_I2C1SEL_Msk (0x3UL << 12)
#define RCC_CCIPR_I2C1SEL_SYSCLK (0x1UL << 12)

#define RCC_BDCR_RTCEN (0x1UL << 15)
#define RCC_BDCR_RTCSEL_Msk (0x3UL << 8)
#define RCC_BDCR_RTCSEL_LSE (0x1UL << 8)
#define RCC_BDCR_LSESYSDIS (0x1UL << 7)
#define RCC_BDCR_LSEDRV_Msk (0x3UL << 3)
#define RCC_BDCR_LSEDRV_HIGHEST_DRIVE RCC_BDCR_LSEDRV_Msk
#define RCC_BDCR_LSERDY (0x1UL << 1)
#define RCC_BDCR_LSEON 0x1UL



#endif /*RCC_H*/